spring:
  application:
    name: shop-app

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  upload:
    product-images: uploads/products

server:
  port: 8080